# data_seeding.py - Full Global Teams, 18-20 Teams Domestic Leagues & 23-Man Squad Engine

NATIONAL_TEAMS = [
    # --- CONMEBOL (South America) ---
    ('Argentina', 'National', 'Argentina', 'CONMEBOL', 92, 1, 'FIFA World Cup'),
    ('Brazil', 'National', 'Brazil', 'CONMEBOL', 90, 5, 'FIFA World Cup'),
    ('Colombia', 'National', 'Colombia', 'CONMEBOL', 86, 9, 'FIFA World Cup'),
    ('Uruguay', 'National', 'Uruguay', 'CONMEBOL', 85, 11, 'FIFA World Cup'),
    ('Ecuador', 'National', 'Ecuador', 'CONMEBOL', 80, 27, 'FIFA World Cup'),
    ('Chile', 'National', 'Chile', 'CONMEBOL', 78, 43, 'FIFA World Cup'),
    ('Peru', 'National', 'Peru', 'CONMEBOL', 77, 42, 'FIFA World Cup'),
    ('Venezuela', 'National', 'Venezuela', 'CONMEBOL', 76, 54, 'FIFA World Cup'),
    ('Paraguay', 'National', 'Paraguay', 'CONMEBOL', 75, 62, 'FIFA World Cup'),
    ('Bolivia', 'National', 'Bolivia', 'CONMEBOL', 70, 84, 'FIFA World Cup'),

    # --- UEFA (Europe) ---
    ('France', 'National', 'France', 'UEFA', 91, 2, 'FIFA World Cup / UEFA Euro'),
    ('Spain', 'National', 'Spain', 'UEFA', 90, 3, 'FIFA World Cup / UEFA Euro'),
    ('England', 'National', 'England', 'UEFA', 89, 4, 'FIFA World Cup / UEFA Euro'),
    ('Belgium', 'National', 'Belgium', 'UEFA', 86, 6, 'FIFA World Cup / UEFA Euro'),
    ('Netherlands', 'National', 'Netherlands', 'UEFA', 87, 7, 'FIFA World Cup / UEFA Euro'),
    ('Portugal', 'National', 'Portugal', 'UEFA', 88, 8, 'FIFA World Cup / UEFA Euro'),
    ('Italy', 'National', 'Italy', 'UEFA', 86, 10, 'FIFA World Cup / UEFA Euro'),
    ('Germany', 'National', 'Germany', 'UEFA', 88, 12, 'FIFA World Cup / UEFA Euro'),
    ('Croatia', 'National', 'Croatia', 'UEFA', 84, 13, 'FIFA World Cup / UEFA Euro'),
    ('Switzerland', 'National', 'Switzerland', 'UEFA', 82, 15, 'FIFA World Cup / UEFA Euro'),
    ('Denmark', 'National', 'Denmark', 'UEFA', 81, 21, 'FIFA World Cup / UEFA Euro'),
    ('Austria', 'National', 'Austria', 'UEFA', 80, 22, 'FIFA World Cup / UEFA Euro'),
    ('Ukraine', 'National', 'Ukraine', 'UEFA', 79, 25, 'FIFA World Cup / UEFA Euro'),
    ('Turkey', 'National', 'Turkey', 'UEFA', 79, 26, 'FIFA World Cup / UEFA Euro'),
    ('Poland', 'National', 'Poland', 'UEFA', 78, 28, 'FIFA World Cup / UEFA Euro'),
    ('Sweden', 'National', 'Sweden', 'UEFA', 78, 29, 'FIFA World Cup / UEFA Euro'),
    ('Wales', 'National', 'Wales', 'UEFA', 76, 30, 'FIFA World Cup / UEFA Euro'),
    ('Hungary', 'National', 'Hungary', 'UEFA', 77, 31, 'FIFA World Cup / UEFA Euro'),
    ('Scotland', 'National', 'Scotland', 'UEFA', 76, 39, 'FIFA World Cup / UEFA Euro'),
    ('Norway', 'National', 'Norway', 'UEFA', 79, 47, 'FIFA World Cup / UEFA Euro'),

    # --- AFC (Asia) ---
    ('Japan', 'National', 'Japan', 'AFC', 85, 18, 'FIFA World Cup / AFC Asian Cup'),
    ('Iran', 'National', 'Iran', 'AFC', 81, 20, 'FIFA World Cup / AFC Asian Cup'),
    ('South Korea', 'National', 'South Korea', 'AFC', 83, 23, 'FIFA World Cup / AFC Asian Cup'),
    ('Australia', 'National', 'Australia', 'AFC', 80, 24, 'FIFA World Cup / AFC Asian Cup'),
    ('Qatar', 'National', 'Qatar', 'AFC', 77, 34, 'FIFA World Cup / AFC Asian Cup'),
    ('Saudi Arabia', 'National', 'Saudi Arabia', 'AFC', 78, 56, 'FIFA World Cup / AFC Asian Cup'),
    ('Iraq', 'National', 'Iraq', 'AFC', 75, 58, 'FIFA World Cup / AFC Asian Cup'),
    ('Uzbekistan', 'National', 'Uzbekistan', 'AFC', 74, 60, 'FIFA World Cup / AFC Asian Cup'),
    ('UAE', 'National', 'UAE', 'AFC', 72, 69, 'FIFA World Cup / AFC Asian Cup'),
    ('Jordan', 'National', 'Jordan', 'AFC', 73, 70, 'FIFA World Cup / AFC Asian Cup'),
    ('Oman', 'National', 'Oman', 'AFC', 71, 76, 'FIFA World Cup / AFC Asian Cup'),
    ('Bahrain', 'National', 'Bahrain', 'AFC', 70, 80, 'FIFA World Cup / AFC Asian Cup'),
    ('China', 'National', 'China', 'AFC', 69, 88, 'FIFA World Cup / AFC Asian Cup'),
    ('Syria', 'National', 'Syria', 'AFC', 68, 89, 'FIFA World Cup / AFC Asian Cup'),
    ('Thailand', 'National', 'Thailand', 'AFC', 73, 101, 'FIFA World Cup / AFC Asian Cup'),
    ('Tajikistan', 'National', 'Tajikistan', 'AFC', 67, 103, 'FIFA World Cup / AFC Asian Cup'),
    ('Kyrgyzstan', 'National', 'Kyrgyzstan', 'AFC', 66, 104, 'FIFA World Cup / AFC Asian Cup'),
    ('Vietnam', 'National', 'Vietnam', 'AFC', 69, 115, 'FIFA World Cup / AFC Asian Cup'),
    ('North Korea', 'National', 'North Korea', 'AFC', 67, 118, 'FIFA World Cup / AFC Asian Cup'),
    ('Indonesia', 'National', 'Indonesia', 'AFC', 68, 133, 'FIFA World Cup / AFC Asian Cup'),
    ('Malaysia', 'National', 'Malaysia', 'AFC', 67, 134, 'FIFA World Cup / AFC Asian Cup'),
    ('Kuwait', 'National', 'Kuwait', 'AFC', 65, 136, 'FIFA World Cup / AFC Asian Cup'),
    ('Philippines', 'National', 'Philippines', 'AFC', 64, 145, 'FIFA World Cup / AFC Asian Cup'),
    ('Singapore', 'National', 'Singapore', 'AFC', 62, 161, 'FIFA World Cup / AFC Asian Cup'),

    # --- CAF (Africa) ---
    ('Morocco', 'National', 'Morocco', 'CAF', 84, 14, 'FIFA World Cup'),
    ('Senegal', 'National', 'Senegal', 'CAF', 83, 19, 'FIFA World Cup'),
    ('Egypt', 'National', 'Egypt', 'CAF', 80, 36, 'FIFA World Cup'),
    ('Nigeria', 'National', 'Nigeria', 'CAF', 81, 39, 'FIFA World Cup'),
    ('Algeria', 'National', 'Algeria', 'CAF', 79, 41, 'FIFA World Cup'),
    ('Cameroon', 'National', 'Cameroon', 'CAF', 77, 49, 'FIFA World Cup'),
    ('Ivory Coast', 'National', 'Ivory Coast', 'CAF', 82, 50, 'FIFA World Cup'),
    ('Mali', 'National', 'Mali', 'CAF', 76, 53, 'FIFA World Cup'),
    ('Tunisia', 'National', 'Tunisia', 'CAF', 76, 57, 'FIFA World Cup'),
    ('Ghana', 'National', 'Ghana', 'CAF', 75, 64, 'FIFA World Cup'),

    # --- CONCACAF (North & Central America) ---
    ('USA', 'National', 'USA', 'CONCACAF', 81, 16, 'FIFA World Cup'),
    ('Mexico', 'National', 'Mexico', 'CONCACAF', 82, 17, 'FIFA World Cup'),
    ('Canada', 'National', 'Canada', 'CONCACAF', 78, 40, 'FIFA World Cup'),
    ('Panama', 'National', 'Panama', 'CONCACAF', 75, 35, 'FIFA World Cup'),
    ('Costa Rica', 'National', 'Costa Rica', 'CONCACAF', 74, 48, 'FIFA World Cup'),
    ('Jamaica', 'National', 'Jamaica', 'CONCACAF', 72, 61, 'FIFA World Cup'),

    # --- OFC (Oceania) ---
    ('New Zealand', 'National', 'New Zealand', 'OFC', 72, 94, 'FIFA World Cup'),
    ('Fiji', 'National', 'Fiji', 'OFC', 58, 166, 'FIFA World Cup')
]

CLUB_TEAMS = [
    # --- Thai League 1 (18 Teams) ---
    ('Buriram United', 'Club', 'Thailand', 'AFC', 75, 0, 'Thai League 1'),
    ('BG Pathum United', 'Club', 'Thailand', 'AFC', 73, 0, 'Thai League 1'),
    ('Port FC', 'Club', 'Thailand', 'AFC', 72, 0, 'Thai League 1'),
    ('Bangkok United', 'Club', 'Thailand', 'AFC', 74, 0, 'Thai League 1'),
    ('Muangthong United', 'Club', 'Thailand', 'AFC', 71, 0, 'Thai League 1'),
    ('Chiangrai United', 'Club', 'Thailand', 'AFC', 70, 0, 'Thai League 1'),
    ('Chonburi FC', 'Club', 'Thailand', 'AFC', 69, 0, 'Thai League 1'),
    ('Ratchaburi FC', 'Club', 'Thailand', 'AFC', 70, 0, 'Thai League 1'),
    ('Uthai Thani FC', 'Club', 'Thailand', 'AFC', 68, 0, 'Thai League 1'),
    ('Khon Kaen United', 'Club', 'Thailand', 'AFC', 67, 0, 'Thai League 1'),
    ('Lamphun Warriors', 'Club', 'Thailand', 'AFC', 68, 0, 'Thai League 1'),
    ('PT Prachuap FC', 'Club', 'Thailand', 'AFC', 67, 0, 'Thai League 1'),
    ('Sukhothai FC', 'Club', 'Thailand', 'AFC', 67, 0, 'Thai League 1'),
    ('Nakhon Pathom United', 'Club', 'Thailand', 'AFC', 66, 0, 'Thai League 1'),
    ('Rayong FC', 'Club', 'Thailand', 'AFC', 65, 0, 'Thai League 1'),
    ('Nongbua Pitchaya', 'Club', 'Thailand', 'AFC', 66, 0, 'Thai League 1'),
    ('Nakhon Ratchasima FC', 'Club', 'Thailand', 'AFC', 66, 0, 'Thai League 1'),
    ('Police Tero FC', 'Club', 'Thailand', 'AFC', 67, 0, 'Thai League 1'),

    # --- J1 League (18 Teams) ---
    ('Kawasaki Frontale', 'Club', 'Japan', 'AFC', 78, 0, 'J1 League'),
    ('Yokohama F. Marinos', 'Club', 'Japan', 'AFC', 78, 0, 'J1 League'),
    ('Vissel Kobe', 'Club', 'Japan', 'AFC', 79, 0, 'J1 League'),
    ('Urawa Red Diamonds', 'Club', 'Japan', 'AFC', 77, 0, 'J1 League'),
    ('Sanfrecce Hiroshima', 'Club', 'Japan', 'AFC', 77, 0, 'J1 League'),
    ('Kashima Antlers', 'Club', 'Japan', 'AFC', 76, 0, 'J1 League'),
    ('Nagoya Grampus', 'Club', 'Japan', 'AFC', 75, 0, 'J1 League'),
    ('Gamba Osaka', 'Club', 'Japan', 'AFC', 75, 0, 'J1 League'),
    ('FC Tokyo', 'Club', 'Japan', 'AFC', 75, 0, 'J1 League'),
    ('Cerezo Osaka', 'Club', 'Japan', 'AFC', 75, 0, 'J1 League'),
    ('Avispa Fukuoka', 'Club', 'Japan', 'AFC', 74, 0, 'J1 League'),
    ('Machida Zelvia', 'Club', 'Japan', 'AFC', 74, 0, 'J1 League'),
    ('Hokkaido Consadole Sapporo', 'Club', 'Japan', 'AFC', 73, 0, 'J1 League'),
    ('Shonan Bellmare', 'Club', 'Japan', 'AFC', 72, 0, 'J1 League'),
    ('Kyoto Sanga', 'Club', 'Japan', 'AFC', 72, 0, 'J1 League'),
    ('Albirex Niigata', 'Club', 'Japan', 'AFC', 73, 0, 'J1 League'),
    ('Kashiwa Reysol', 'Club', 'Japan', 'AFC', 73, 0, 'J1 League'),
    ('Sagan Tosu', 'Club', 'Japan', 'AFC', 71, 0, 'J1 League'),

    # --- Premier League (20 Teams) ---
    ('Manchester City', 'Club', 'England', 'UEFA', 92, 0, 'Premier League'),
    ('Arsenal', 'Club', 'England', 'UEFA', 89, 0, 'Premier League'),
    ('Liverpool', 'Club', 'England', 'UEFA', 89, 0, 'Premier League'),
    ('Chelsea', 'Club', 'England', 'UEFA', 84, 0, 'Premier League'),
    ('Manchester United', 'Club', 'England', 'UEFA', 83, 0, 'Premier League'),
    ('Tottenham Hotspur', 'Club', 'England', 'UEFA', 83, 0, 'Premier League'),
    ('Newcastle United', 'Club', 'England', 'UEFA', 82, 0, 'Premier League'),
    ('Aston Villa', 'Club', 'England', 'UEFA', 82, 0, 'Premier League'),
    ('Brighton', 'Club', 'England', 'UEFA', 80, 0, 'Premier League'),
    ('West Ham United', 'Club', 'England', 'UEFA', 79, 0, 'Premier League'),
    ('Wolverhampton', 'Club', 'England', 'UEFA', 78, 0, 'Premier League'),
    ('Crystal Palace', 'Club', 'England', 'UEFA', 78, 0, 'Premier League'),
    ('Fulham', 'Club', 'England', 'UEFA', 77, 0, 'Premier League'),
    ('Bournemouth', 'Club', 'England', 'UEFA', 77, 0, 'Premier League'),
    ('Brentford', 'Club', 'England', 'UEFA', 77, 0, 'Premier League'),
    ('Everton', 'Club', 'England', 'UEFA', 76, 0, 'Premier League'),
    ('Nottingham Forest', 'Club', 'England', 'UEFA', 76, 0, 'Premier League'),
    ('Leicester City', 'Club', 'England', 'UEFA', 75, 0, 'Premier League'),
    ('Southampton', 'Club', 'England', 'UEFA', 74, 0, 'Premier League'),
    ('Ipswich Town', 'Club', 'England', 'UEFA', 73, 0, 'Premier League'),

    # --- La Liga (20 Teams) ---
    ('Real Madrid', 'Club', 'Spain', 'UEFA', 93, 0, 'La Liga'),
    ('FC Barcelona', 'Club', 'Spain', 'UEFA', 89, 0, 'La Liga'),
    ('Atletico Madrid', 'Club', 'Spain', 'UEFA', 86, 0, 'La Liga'),
    ('Athletic Bilbao', 'Club', 'Spain', 'UEFA', 82, 0, 'La Liga'),
    ('Real Sociedad', 'Club', 'Spain', 'UEFA', 81, 0, 'La Liga'),
    ('Real Betis', 'Club', 'Spain', 'UEFA', 80, 0, 'La Liga'),
    ('Villarreal', 'Club', 'Spain', 'UEFA', 81, 0, 'La Liga'),
    ('Sevilla FC', 'Club', 'Spain', 'UEFA', 79, 0, 'La Liga'),
    ('Girona FC', 'Club', 'Spain', 'UEFA', 81, 0, 'La Liga'),
    ('Valencia CF', 'Club', 'Spain', 'UEFA', 77, 0, 'La Liga'),
    ('Osasuna', 'Club', 'Spain', 'UEFA', 76, 0, 'La Liga'),
    ('Getafe CF', 'Club', 'Spain', 'UEFA', 75, 0, 'La Liga'),
    ('Celta Vigo', 'Club', 'Spain', 'UEFA', 76, 0, 'La Liga'),
    ('Rayo Vallecano', 'Club', 'Spain', 'UEFA', 75, 0, 'La Liga'),
    ('Mallorca', 'Club', 'Spain', 'UEFA', 75, 0, 'La Liga'),
    ('Espanyol', 'Club', 'Spain', 'UEFA', 74, 0, 'La Liga'),
    ('Deportivo Alaves', 'Club', 'Spain', 'UEFA', 74, 0, 'La Liga'),
    ('UD Las Palmas', 'Club', 'Spain', 'UEFA', 73, 0, 'La Liga'),
    ('Real Valladolid', 'Club', 'Spain', 'UEFA', 72, 0, 'La Liga'),
    ('CD Leganes', 'Club', 'Spain', 'UEFA', 72, 0, 'La Liga')
]

REAL_MANAGERS = {
    'Thailand': ('Anthony Hudson', 'Balanced'),
    'Japan': ('Hajime Moriyasu', 'Counter'),
    'South Korea': ('Hong Myung-bo', 'Possession'),
    'England': ('Thomas Tuchel', 'Attacking'),
    'Spain': ('Luis de la Fuente', 'Positional'),
    'Argentina': ('Lionel Scaloni', 'Adaptive'),
    'France': ('Didier Deschamps', 'Defensive'),
    'Brazil': ('Dorival Junior', 'Attacking'),
    'Germany': ('Julian Nagelsmann', 'Gegenpress'),
    'Manchester City': ('Pep Guardiola', 'Positional'),
    'Arsenal': ('Mikel Arteta', 'Possession'),
    'Liverpool': ('Arne Slot', 'Attacking'),
    'Real Madrid': ('Carlo Ancelotti', 'Adaptive'),
    'FC Barcelona': ('Hansi Flick', 'Gegenpress'),
    'Buriram United': ('Osmar Loss', 'Balanced')
}

STAR_PLAYERS = {
    'Thailand': [('Chanathip Songkrasin', 'CAM'), ('Supachai Chaided', 'ST'), ('Supachok Sarachat', 'LW'), ('Patiwat Khammai', 'GK'), ('Theerathon Bunmathan', 'LB')],
    'Japan': [('Kaoru Mitoma', 'LW'), ('Takefusa Kubo', 'RW'), ('Wataru Endo', 'CDM'), ('Takumi Minamino', 'CAM'), ('Zion Suzuki', 'GK')],
    'England': [('Harry Kane', 'ST'), ('Jude Bellingham', 'CAM'), ('Bukayo Saka', 'RW'), ('Declan Rice', 'CDM'), ('Jordan Pickford', 'GK')],
    'France': [('Kylian Mbappe', 'ST'), ('Antoine Griezmann', 'CAM'), ('Ousmane Dembele', 'RW'), ('Aurelien Tchouameni', 'CDM'), ('Mike Maignan', 'GK')],
    'Argentina': [('Lionel Messi', 'RW'), ('Julian Alvarez', 'ST'), ('Alexis Mac Allister', 'CM'), ('Rodrigo De Paul', 'CM'), ('Emiliano Martinez', 'GK')],
    'Spain': [('Lamine Yamal', 'RW'), ('Nico Williams', 'LW'), ('Rodri', 'CDM'), ('Pedri', 'CM'), ('Unai Simon', 'GK')],
    'Brazil': [('Vinicius Jr', 'LW'), ('Rodrygo', 'RW'), ('Endrick', 'ST'), ('Bruno Guimaraes', 'CM'), ('Alisson Becker', 'GK')],
    'Manchester City': [('Erling Haaland', 'ST'), ('Kevin De Bruyne', 'CAM'), ('Phil Foden', 'RW'), ('Rodri', 'CDM'), ('Ederson', 'GK')],
    'Real Madrid': [('Kylian Mbappe', 'ST'), ('Vinicius Jr', 'LW'), ('Jude Bellingham', 'CAM'), ('Federico Valverde', 'CM'), ('Thibaut Courtois', 'GK')],
    'FC Barcelona': [('Lamine Yamal', 'RW'), ('Robert Lewandowski', 'ST'), ('Pedri', 'CM'), ('Gavi', 'CM'), ('Marc-Andre ter Stegen', 'GK')],
    'Liverpool': [('Mohamed Salah', 'RW'), ('Virgil van Dijk', 'CB'), ('Trent Alexander-Arnold', 'RB'), ('Alexis Mac Allister', 'CM'), ('Alisson Becker', 'GK')],
    'Buriram United': [('Guilherme Bissoli', 'ST'), ('Lucas Crispim', 'CAM'), ('Goran Causic', 'CM'), ('Curtis Good', 'CB'), ('Siwarak Tedsungnoen', 'GK')]
}

TROPHIES_HISTORY_SAMPLES = [
    ('FIFA World Cup', 2022, 'Argentina', 'France', '3 - 3 (p 4-2)'),
    ('UEFA Euro', 2024, 'Spain', 'England', '2 - 1'),
    ('AFC Asian Cup', 2023, 'Qatar', 'Jordan', '3 - 1'),
    ('Premier League', 2024, 'Manchester City', 'Arsenal', '91 Pts'),
    ('La Liga', 2024, 'Real Madrid', 'FC Barcelona', '95 Pts'),
    ('Thai League 1', 2024, 'Buriram United', 'Bangkok United', '69 Pts')
]
